# Generated by Django 5.2.1 on 2025-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_system', '0002_userprofile_is_ict_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_service_desk',
            field=models.BooleanField(default=False),
        ),
    ]
