# Generated by Django 5.2.1 on 2025-06-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_system', '0003_userprofile_is_service_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='affected_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_dept', to='reset_system.department'),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='affected_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='affected_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='is_ad_account',
            field=models.BooleanField(default=False),
        ),
    ]
