# Generated by Django 5.2.1 on 2025-06-18 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_system', '0004_passwordresetrequest_affected_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='affected_director',
            field=models.ForeignKey(blank=True, help_text='Deputy Director responsible for approving this AD reset request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_requests_directed', to=settings.AUTH_USER_MODEL),
        ),
    ]
